### ISSUE TITLE
 ERROR  could not get team information. 404 - Not found

### ISSUE THREAD

**Issue by puskartritalwebo** [cometkim/turbocache#3]
I've cloned this repo and did as suggested and in another repo i did npx turbo build with api url, team name and token (which is i believe same as secret_key that i used from readme.md), still im not able to use it can you please suggest me some ideas on this what i am doing wrong?

[![Screenshot-from-2022-12-16-18-47-15.png](https://i.postimg.cc/gcRKMP9G/Screenshot-from-2022-12-16-18-47-15.png)](https://postimg.cc/xqfHChTZ)

Figured out i was missing turbo.json hope this will help someone.

**Comment by puskartritalwebo** [comment]
this was silly mistake since i was missing turbo.json.

**Comment by yevhen-logosha** [comment]
hey @puskartritalwebo getting same error, only difference is I have `turbo.json` present. Anything specific you have added to that file ? thanks
